version: '3'

services:
  db:
    image: postgres:16.1
    env_file:
      - .env
  web:
    env_file:
      - .env
    depends_on:
      - db
      - pgadmin
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: ['gunicorn', 'backend.wsgi:application', '--bind', '0.0.0.0:8000']

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - '5050:80'
    depends_on:
      - db
